import { CreateCategoryDto } from '../../categories/dto/create-category.dto';

export const defaultCategories: CreateCategoryDto[] = [
  { name: 'Gaming', icon: '🎮' },
  { name: 'Programming', icon: '💻' },
  { name: 'Artificial Intelligence', icon: '🤖' },
  { name: 'Anime', icon: '🎌' },
  { name: 'Music', icon: '🎵' },
  { name: 'Photography', icon: '📸' },
  { name: 'Art & Design', icon: '🎨' },
  { name: 'Movies', icon: '🎬' },
  { name: 'TV Shows', icon: '📺' },
  { name: 'Manga', icon: '📖' },
  { name: 'Science', icon: '🔬' },
  { name: 'Technology', icon: '⚙️' },
  { name: 'Education', icon: '📚' },
  { name: 'Business', icon: '💼' },
  { name: 'Startups', icon: '🚀' },
  { name: 'Finance', icon: '💰' },
  { name: 'Cryptocurrency', icon: '₿' },
  { name: 'Trading', icon: '📈' },
  { name: 'Sports', icon: '⚽' },
  { name: 'Fitness', icon: '💪' },
  { name: 'Health', icon: '🩺' },
  { name: 'Food', icon: '🍕' },
  { name: 'Cooking', icon: '🍳' },
  { name: 'Travel', icon: '✈️' },
  { name: 'Cars', icon: '🚗' },
  { name: 'Motorcycles', icon: '🏍️' },
  { name: 'Photography Gear', icon: '📷' },
  { name: 'Nature', icon: '🌿' },
  { name: 'Pets', icon: '🐾' },
  { name: 'Fashion', icon: '👗' },
  { name: 'Beauty', icon: '💄' },
  { name: 'Memes', icon: '😂' },
  { name: 'Entertainment', icon: '🎭' },
  { name: 'Streaming', icon: '📡' },
  { name: 'Content Creators', icon: '🎥' },
  { name: 'Discord Bots', icon: '🤖' },
  { name: 'Web Development', icon: '🌐' },
  { name: 'Mobile Development', icon: '📱' },
  { name: 'Cybersecurity', icon: '🛡️' },
  { name: 'Open Source', icon: '❤️' },
  { name: 'Robotics', icon: '🦾' },
  { name: 'Military', icon: '🪖' },
  { name: 'Roleplay', icon: '🎭' },
  { name: 'Minecraft', icon: '⛏️' },
  { name: 'Valorant', icon: '🎯' },
  { name: 'CS2', icon: '🔫' },
  { name: 'League of Legends', icon: '🏆' },
  { name: 'Roblox', icon: '🧱' },
  { name: 'Fortnite', icon: '🏝️' },
  { name: 'Community', icon: '👥' },
];